### ISSUE TITLE
Add more debug and error logging

### ISSUE THREAD

**Issue by osnard** [hallowelt/mwstake-mediawiki-component-processmanager#12]
It is quite difficult to find the root cause of issues with this component, as the log is very bare bone.

At lease the command that get's executed by a step needs to be shown. Ideally also some context data.

**Comment by it-spiderman** [comment]
in V3.0.1 more debugging info is added to ProcessRunner log channel. 
Note that PR can only know about input and output of the step/process, for any specific logging within step, step itself must implement it
